<?php

/**
 * @file
 * Read and Write Jekyll files.
 */
require DRUPAL_ROOT . '/profiles/dekyll/libraries/vendor/autoload.php';

use GitWrapper\GitWrapper;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Yaml\Parser;

function dekyll_parser_init() {
  $wrapper = new GitWrapper();

  $path = variable_get('file_public_path', conf_path() . '/files') . '/git';

  $git = $wrapper->workingCopy($path);
  if (!$git->isCloned()) {
    $git->clone('git@github.com:amitaibu/jekyll-bootstrap.git');
  }

  // Find files.
  $finder = new Finder();
  $finder
    ->files()
    ->in($path)
    // @todo: Exclude directories with underscore except of _posts and _drafts
    ->notPath('/^_.*/')
    ->notPath('assets');


  foreach ($finder as $file) {
    if ($file->getFilename() === 'archive.html') {
      $contents = $file->getContents();

      // Get the values from the YAML front header.
      $split_contents = explode("---\n", $contents);
      $yaml_contents = $split_contents[1];


      $yaml = new Parser();
      $value = $yaml->parse($yaml_contents);
      dpm($value);

      return;
    }
  }

}
