<?php
/**
 * @file
 * Code for the Dekyll Post feature.
 */

include_once 'dekyll_post.features.inc';

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dekyll_post_form_node_form_alter(&$form, $form_state, $form_id) {
  $node = $form['#node'];
  if (!og_is_group_content_type('node', $node->type)) {
    return;
  }

  _dekyll_post_disable_branch($form, $form_state);

}

/**
 * Disable the "branch" field to prevent it from changing on existing nodes.
 */
function _dekyll_post_disable_branch(&$form, $form_state) {
  $node = $form['#node'];

  if (empty($node->nid)) {
    return;
  }

  $element = &$form[OG_VOCAB_FIELD][LANGUAGE_NONE][0];

  // Get the "branch" vocabulary.
  $vids = array();
  foreach (array_keys($element) as $key) {
    if (is_numeric($key)) {
      $vids[] = $key;
    }
  }

  $vocabularies = taxonomy_vocabulary_load_multiple($vids);
  foreach ($vocabularies as $vocabulary) {
    if ($vocabulary->name != 'branch') {
      continue;
    }

    $element[$vocabulary->vid]['#disabled'] = TRUE;
    // We can return.
    return;
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Help the file name creation for post content type.
 *
 * @todo: Add validate to make sure file is under _posts.
 */
function dekyll_post_form_post_node_form_alter(&$form, $form_state, $form_id) {
  $file_path_parts = array();

  if ($default_value = &$form['field_file_path'][LANGUAGE_NONE][0]['value']['#default_value']) {
    $file_path_parts = explode('/', $default_value, 2);

    $path_info = pathinfo(substr($file_path_parts[1], 11));

    $default_value = $path_info['filename'];
    $extension = $path_info['extension'];
  }
  else {
    $extension = 'md';
  }

  // Add elements to select the directory and date prefix of the post file.
  $element = array();
  $element['directory'] = array(
    '#title' => t('Directory'),
    '#title_display' => 'invisible',
    '#type' => 'select',
    '#options' => array(
      '_posts' => '_posts',
      '_drafts' => '_drafts',
    ),
    '#weight' => -10,
    '#default_value' => !empty($file_path_parts) ? $file_path_parts[0] : '_posts',
  );

  $element['file_date'] = array(
    '#title' => t('File date'),
    '#title_display' => 'invisible',
    '#date_label_position' => 'invisible',
    '#type' => 'date_popup',
    '#date_format' => 'Y-m-d',
    '#weight' => -5,
    '#default_value' => !empty($file_path_parts) ? substr($file_path_parts[1], 0, 10) : date('Y-m-d'),
    '#size' => 10,
    '#prefix' => '<div class="prefix-float">/</div>',
    '#suffix' => '<div class="suffix-float">-</div>',

    // Hide this field, if "_drafts" folder is selected, as the date isn't
    // needed on that folder (since the post isn't published yet).
    '#states' => array(
      'visible' => array(   // action to take.
        ':input[name="field_file_path[und][0][directory]"]' => array('value' => '_posts'),
      ),
    ),

  );

  $element['extension'] = array(
    '#title' => t('Extension'),
    '#title_display' => 'invisible',
    '#type' => 'select',
    '#options' => array(
      'md' => 'md',
      'html' => 'html',
    ),
    '#default_value' => $extension,
    '#weight' => 10,
    '#prefix' => '<div class="prefix-float">.</div>',
  );

  $form['field_file_path'][LANGUAGE_NONE][0] += $element;
  $form['field_file_path'][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
  $form['field_file_path'][LANGUAGE_NONE][0]['value']['#attached']['js'][] = drupal_get_path('module', 'dekyll_post') . '/js/dekyll_post.js';
  $form['field_file_path'][LANGUAGE_NONE][0]['value']['#attached']['css'][] = drupal_get_path('module', 'dekyll_post') . '/css/dekyll_post.css';

  // Allow floating the inner elements.
  $form['field_file_path']['#attributes']['class'][] = 'clearfix';

  $form['field_file_path'][LANGUAGE_NONE][0]['value']['#element_validate'][] = 'dekyll_post_field_file_path_element_validate';
}

/**
 * Element validate; Prefix the file name with "_posts".
 */
function dekyll_post_field_file_path_element_validate($element, &$form_state) {
  $values = $form_state['values']['field_file_path'][LANGUAGE_NONE][0];

  $file_date = $values['directory'] == '_posts' ? $values['file_date']['date'] . '-' : '';
  $file_path = $values['directory'] . '/' . $file_date . $values['value'] . '.' . $values['extension'];
  form_set_value($element, $file_path, $form_state);
}
