<?php
/**
 * @file
 * Code for the Dekyll OG feature.
 */

include_once 'dekyll_repository.features.inc';

/**
 * Get the branch name from a group content.
 */
function dekyll_repository_get_git_branch($node) {
  $wrapper = entity_metadata_wrapper('node', $node);

  $gid = $wrapper->{OG_AUDIENCE_FIELD}->value(array('identifier' => TRUE));

  $vocabulary = taxonomy_vocabulary_machine_name_load('branch_' . $gid);
  foreach ($wrapper->{OG_VOCAB_FIELD}->value() as $term) {
    if ($term->vid == $vocabulary->vid) {
      return $term->name;
    }
  }
}

/**
 * Implements hook_node_insert()
 *
 * Add queue item to clone repo.
 */
function dekyll_repository_node_insert($node) {
  if ($node->type != 'repository') {
    return;
  }

  // When cloning, the default branch will be auto-created.
  $queue = DrupalQueue::get('dekyll_clone');
  $data = array(
    'gid' => $node->nid,
  );
  $queue->createItem($data);
}

/**
 * Return the repository path.
 *
 * @param $nid
 *   The node ID of the repository or page.
 *
 * @return
 *   The relative path.
 */
function dekyll_repository_get_repo_path($nid) {
  $wrapper = entity_metadata_wrapper('node', $nid);

  if (isset($wrapper->{OG_AUDIENCE_FIELD})) {
    $wrapper = $wrapper->{OG_AUDIENCE_FIELD};
  }

  $repository = str_replace(array('http://', 'https://'), '', $wrapper->field_repo_url->value());
  return variable_get('file_public_path', conf_path() . '/files') . '/' . $repository;
}
