<?php

/**
 * Implements hook_migrate_api().
 */
function imanimo_migrate_migrate_api() {
  $class_names = array();

  $migrations = array(
    // Commerce product.
    'ImanimoProductCommerceProducts',

    // Node.
    'ImanimoBranchNodes',
    'ImanimoPageNodes',
    'ImanimoProductPageNodes',
    'ImanimoRepositoryNodes',

    // Taxonomy term.
    'ImanimoColorTerms',
    'ImanimoSizeTerms',
  );

  foreach ($class_names as $class_name) {
    $migrations[$class_name] = array('class_name' => $class_name);
  }

  $api = array(
    'api' => 2,
    'migrations' => $migrations,
  );

  return $api;
}
